### ISSUE TITLE
Ensure we're testing against the right version(s) of Chrome

### ISSUE THREAD

**Issue by inglesp** [opensafely-core/airlock#114]
Users will access Airlock through a web browser.  In the TPP secure environment, Chrome and Firefox are available, but the old version of Firefox doesn't support features we need.  As such we will document that users must use Chrome.

We should ensure that our playwright tests test against the same version of Chrome.

**Comment by madwort** [comment]
looks like Becky has done some of this in https://github.com/ebmdatalab/team-manual/pull/650
