### ISSUE TITLE
Allow researchers to withdraw files from a request

### ISSUE THREAD

**Issue by inglesp** [opensafely-core/airlock#138]
A researcher may want to withdraw a file from a request, either because they submitted it by mistake, or because it has been rejected by a reviewer.

#136 describes how this fits in to the full release request lifecycle.

Depends on #137.

**Comment by madwort** [comment]
note to self - probably want to keep the file on disk in the request, just mark it as withdrawn & hide it sometimes (tbc)

**Comment by bloodearnest** [comment]
Fixed in #202
