### ISSUE TITLE
Add telemetry to airlock

### ISSUE THREAD

**Issue by bloodearnest** [opensafely-core/airlock#181]
Add basic django otel requests, we can even emit them in prod via our gateway on dokku4.

Be worth adding some manual measurements to the trace too, like how long it takes the tree to build, whether its htmx request or not

 * [x] - Install/configure django/requests opentelemetry in airlock
 * [x] - Add some custom measurements (tree construction, rendering)
 * [x] - Configure backend-server to emit this data to the right place in honeycomb.

**Comment by bloodearnest** [comment]
[ ] - Install/configure django/requests opentelemetry in airlock
[ ] - Add some custom measurements (tree construction, rendering)
[ ] - Configure backend-server to emit this data to the right place in honeycomb.

**Comment by rebkwok** [comment]
@bloodearnest  Are we done with this ticket (for now), do you think? We have custom measurements on all workspace and request views, and the tree building, but not specifically the file content rendering

**Comment by bloodearnest** [comment]
Yeah, I think so.

I had a look at measuring rendering, but its messy.  Manually decorating works, like `Templater.render = instrument(Template.render)`, but it gives us a *lot* of spans, as every included/recursive template is emitted.


Ideally, we just want to know the total time spend rendering, but I'm not sure how to do that

Happy to close for now, we've got a baseline, and it'll be easy for us to add stuff
