### ISSUE TITLE
Release SRO Measures report

### ISSUE THREAD

**Issue by inglesp** [opensafely-core/airlock#205]
To complete [stepping stone 2](https://github.com/opensafely-core/airlock/milestone/2), we should make sure that @LFISHER7 (or another researcher) is able to request the release of [the SRO Measures report](https://github.com/ebmdatalab/opensafely-output-review/issues/825) and that output checkers are able to review and release it.

**Comment by inglesp** [comment]
Assigning to me for tracking, but @LFISHER7 and the output checkers are doing the work!

**Comment by LFISHER7** [comment]
We're currently [rerunning the report](https://jobs.opensafely.org/service-restoration-observatory/sro-measures-dashboard-updating/22640/) but I hope to be able to try and submit a release request later today

**Comment by LFISHER7** [comment]
I've successfully submitted a request, which is tracked in https://github.com/ebmdatalab/opensafely-output-review/issues/834

**Comment by LFISHER7** [comment]
This has been reviewed and released
