### ISSUE TITLE
Allow selecting multiple files & adding to a group

### ISSUE THREAD

**Issue by madwort** [opensafely-core/airlock#242]
https://bennettoxford.slack.com/archives/C065F8P58AW/p1712755051357289?thread_ts=1712753890.166379&cid=C065F8P58AW

> The main thing that slowed me down was having to select files individually and add them to the request. It would be nice to have select boxes to add multiple at once. I would then select all the output files in a file group, followed by the supporting files for that file group.

**Comment by madwort** [comment]
Louis said that all the clicking was a big time sink for him, so this seems relatively high priority

**Comment by bloodearnest** [comment]
Am going to spike the UI for this first, with no actual functionaity, so we can get a preview.

**Comment by bloodearnest** [comment]
Current status: #331 lays the ground work for this.

Am splitting out some other changes, but getting the UX right for multiselect is complex
