### ISSUE TITLE
Show file timestamp and other metadata

### ISSUE THREAD

**Issue by madwort** [opensafely-core/airlock#243]
https://bennettoxford.slack.com/archives/C065F8P58AW/p1712755051357289?thread_ts=1712753890.166379&cid=C065F8P58AW

> In the file list within a workspace, I would like to be able to see the time the file was last updated, and order them by this date. I often use this to identify the outputs I want.

Other metadata includes file size, and for CSV files, row and column counts.

**Comment by madwort** [comment]
nb. I'm not sure how we square this with the performance considerations around generating the file lists for huge (45k files) workspaces

**Comment by madwort** [comment]
this is for right hand panel (directory view) & for file view, not for tree view.

**Comment by madwort** [comment]
blocked waiting for https://github.com/opensafely-core/job-runner/issues/701#issuecomment-2071807529

**Comment by rebkwok** [comment]
With #315, the timestamp will be available as an attribute on `RequestFile`

**Comment by bloodearnest** [comment]
@madwort I think it might be worth waiting for my in progress multiselect branch to land first, as it adds a full UI for directory view

**Comment by madwort** [comment]
this is done now

**Comment by bloodearnest** [comment]
So, my change just did it for the directory.

We might also want to show it in the header for file view?
