### ISSUE TITLE
Visually distinguish the supporting files in the request view file list

### ISSUE THREAD

**Issue by madwort** [opensafely-core/airlock#246]
https://bennettoxford.slack.com/archives/C065F8P58AW/p1712755051357289?thread_ts=1712753890.166379&cid=C065F8P58AW

> Could the supporting files be distinguished in review request file list (within the file group dropdowns)?

**Comment by madwort** [comment]
these are in italics

**Comment by rebkwok** [comment]
This is already done
![Image](https://github.com/user-attachments/assets/2f6552e6-6639-462f-b774-86486a6384ac)
