### ISSUE TITLE
Page jumps around

### ISSUE THREAD

**Issue by madwort** [opensafely-core/airlock#252]
> the page seemed to jump around a bit when i toggled between files to approve and clicking the 'approve' button

from Rose

**Comment by bloodearnest** [comment]
I think this because all POSTs are full page refreshes currently

I think that per-request level ones should probably still be, but per file ones (like approval) should probably be HTMXified to do partial reload, and not move you around.

**Comment by madwort** [comment]
Hmmm, if you didn't reset the view to the top of the page when e.g. approving a file, you would never see the "File has been approved" message popup. Not that the user really needs to see it, but maybe it could be removed. 

[htmx-oob-swap](https://htmx.org/docs/#oob_swaps) looks interesting for swapping out the tree, although I'm not sure I'd want to try swapping /parts/ of the tree maybe I'd just swap the whole thing. Oh, but would we lose context about what subdirs of the tree are opened? hmmm.

**Comment by bloodearnest** [comment]
Hmm, yeah that's the exact kinda thing that htmx-oob-swap is for.

I guess another alternative is to reload with anchor? Slightly less good UI, but functionally workable? But I'd be keep to try oob thing first, myself

**Comment by madwort** [comment]
Also jumps around if you click a subdirectory, haven't looked into why yet


https://github.com/opensafely-core/airlock/assets/2082895/75f81679-f2c2-484c-ac0f-e6831cd3771b
