### ISSUE TITLE
Cannot log in with github email

### ISSUE THREAD

**Issue by rebkwok** [opensafely-core/airlock#269]
The login form says to login with GitHub username or Email address, but only username works. We should either make both work, or only ask for username.

**Comment by madwort** [comment]
Email works for me, although it accepts the email address attached to my job-server account as per https://github.com/opensafely-core/job-server/blob/88a944ae2884bc9123310e537a16983ebd697d6d/jobserver/commands/users.py#L75  - in my case this is my usual personal email address, which is also the primary email address attached to my Github account but may not be for others. As you would expect from looking at the line in job-server, it does not accept my secondary email address in Github (which is my Datalab address).

**Comment by madwort** [comment]
Maybe it should be "Github username or OpenSAFELY contact email address" (ugh, clumsy wording)

**Comment by rebkwok** [comment]
I think @CLStables mentioned this, and then I checked (with my personal email, which is the right one) but typoed my email address 🤦

@CLStables Can you check if you can log in to airlock with the email address you have in job-server?

**Comment by rebkwok** [comment]
Given that you can change your email address on job-server, it does need to be something other than  "GitHub username or email address".

**Comment by CLStables** [comment]
I don't think it was me who brought this up (or if it was I have no recollection!!). I'm happy to test later today though...
