### ISSUE TITLE
Show progress message/spinner when files are releasing

### ISSUE THREAD

**Issue by rebkwok** [opensafely-core/airlock#270]
Feedback from @milanwiedemann ([slack thread](https://bennettoxford.slack.com/archives/C01UJLWNZJT/p1712917633599879?thread_ts=1712753568.007979&cid=C01UJLWNZJT)):
> for a brief moment after clicking the "Release files" button I didn't know if anythig is happening (this is probalbly because there were so many files in this request). after a couple seconds I started getting notifications from [#opensafely-releases](https://bennettoxford.slack.com/archives/C03KD4LURV4) in slack that the files are being released ... only after ALL files were released I got a green msg on the airlock page that "Files have been released to [jobs.opensafely.org](http://jobs.opensafely.org/)" ... I was thinking that  maybe another msg right after clicking the "Release files" button with a msg like "Files are currently being released to [jobs.opensafely.org](http://jobs.opensafely.org/)" followed by "Files have been successfully released to [jobs.opensafely.org](http://jobs.opensafely.org/)" would be helpful?

**Comment by madwort** [comment]
Minimal version in https://github.com/opensafely-core/airlock/pull/288 

If we wanted to swap out the release button for a grayed out button, I think we could do that by adding an automatic intermediary step using a new request_approve controller (which would change status to approve, return the grayed button saying "releasing" with a spinner & contain `hx-trigger="load" hx-post="{{request_release_url}}` to automatically send the client onwards to do the actual release as currently)
