### ISSUE TITLE
Large CSVs take a long time to render with datatables.

### ISSUE THREAD

**Issue by bloodearnest** [opensafely-core/airlock#280]
Some CSV files are quite large, measures in particular.

Enabling datatables on large CSV can take a long time to render.

For large tables, we should maybe default to rendering them as plain html first, and add a button to enable datatables, with a suitable warning that it may take a while to load?

**Comment by rebkwok** [comment]
I think this can be closed now that we have a limit of 5000 rows on L4 CSVs
