### ISSUE TITLE
Support un-approving/rejecting

### ISSUE THREAD

**Issue by bloodearnest** [opensafely-core/airlock#284]
Users may make a mistake, and want to unapprove or unreject something.

We should add a button to remove any current FileReviews for this file.

It can possibly a pill like we used in SACRO, but with 3 sections?

![Image](https://github.com/opensafely-core/airlock/assets/1042/c033a282-7658-4fde-b513-b26aacceba97)

**Comment by bloodearnest** [comment]
That's a good question, I'm not sure.

Depending on how we do the #254, I am wondering if we do need this. I just originally captured it as part of Catherine's feed back.

However, if we move to a world where to progress, an output-checker has to vote accept/reject on every file, then maybe this isn't needed?

I'd put it on the back burner until we know?

**Comment by madwort** [comment]
Yeah, it's a small qol improvement, but I think it would make life easier for output-checkers regardless of #254. As you say, if we had a "review completed" button then the overall process wouldn't move forward until they'd hit that button - but in terms of completing their own work if they initially approved a file & then had doubts, they would have to store a dirty flag for that file in their brains until they get time to complete the review, whereas if they had a "remove review" button they could quickly do that as a placeholder until they get time to do the work to approve/reject.

**Comment by bloodearnest** [comment]
Yeah, that's good point.

In that case, do we delay audit until submitting the final votes/comments?

And just delete the FileReview?

**Comment by madwort** [comment]
I think we audit everything as it happens - that way we can audit our systems as well as what the users did - so the audit log would look like:
* file x review approved
* file x review deleted
* file x review ...etc...

**Comment by bloodearnest** [comment]
Right, that is simpler.

But the audit trail serves double purpose. It's a forensic trail (for which recording everything makes sense, even if its immediately reversed). But its also a UX element for users to know what activity has happened. In that case, the additional spurious logs could be quite noisy.
