### ISSUE TITLE
Enable deleting or editing of user comments

### ISSUE THREAD

**Issue by bloodearnest** [opensafely-core/airlock#286]
Users might make mistakes (e.g. comment on the wrong group) and want to remove comments.

The two output-checkers might have written conflicting comments, and need tor remove or edit them before communicating to the user.

For all these reasons, we should enable deleting and editing of comments by the comment author.

- [x] deleting comments #317 
- [ ] editing comments

Nb. this is for day-to-day editing of comments, not for redaction. All actions & comment content should be audited in full.

**Comment by inglesp** [comment]
Less necessary now we have private comments
