### ISSUE TITLE
Add machinery for creating a request, and for adding/removing files to the request

### ISSUE THREAD

**Issue by inglesp** [opensafely-core/airlock#29]
A (user, workspace) pair can only have a single current request.

We need pair of functions with the following signatures:

* `add_to_current_request(user: User, workspace: Workspace, path: PathItem) -> None`
* `remove_from_current_request(user: User, workspace: Workspace, path: PathItem) -> None`

If a (user, workspace) has no current request, `add_to_current_request` should create one with status "pending".

Adding a file to a request should copy the file into `settings.WORK_DIR / "staging" / request.id / path`, and removing a file from the request should delete it.

We also need functions that return information about the files in a request:

* `is_in_current_request(user: User, workspace: Workspace, path: PathItem) -> bool`
* `files_in_request(request: Request) -> [PathItem]`

**Comment by evansd** [comment]
Note: changed the path from `settings.WORK_DIR` to `settings.WORK_DIR / "staging"`.

`WORK_DIR` is a general working directory with various things in e.g. the local SQLite database, and these directories should be namespaced.
