### ISSUE TITLE
Automate deployment to test backend

### ISSUE THREAD

**Issue by inglesp** [opensafely-core/airlock#3]
deploy airlock in pretty much the same way we deploy e.g. job-server on test-backend

now split into three tickets:

* https://github.com/opensafely-core/airlock/issues/44
* https://github.com/opensafely-core/airlock/issues/45
* https://github.com/opensafely-core/airlock/issues/46

**Comment by bloodearnest** [comment]
I would recommend basing it off job-server's docker stack. release-hatch has no static assets to manage, so is simpler. Where as, if we want to run as non-root, managing the asset build and collectstatic stuff is a bit more complex.

**Comment by madwort** [comment]
> basing it off job-server's docker stack

excellent point

**Comment by madwort** [comment]
wip https://github.com/opensafely-core/airlock/pull/13
