### ISSUE TITLE
Add machinery for releasing files

### ISSUE THREAD

**Issue by inglesp** [opensafely-core/airlock#30]
We need a pair of functions with the following signatures:

* `release_request(request: Request) -> None`
* `reject_request(request: Request) -> None`

Releasing a request updates its status to "released", and copies the files to job-server.  There is code in release-hatch that can be repurposed for this.

Rejecting a request updates its status to "rejected".

We also need a function that returns all requests with a given status:

* `get_requests(status) -> [Request]`

We should consider using an enum for the status of a request.  (See also #29.)

**Comment by evansd** [comment]
The code which interacts with the Job Server releases API should make sure to set the `tool` field in both the Release and ReleaseFile metadata to `airlock`.

See the equivalent code in `osrelease` here:
https://github.com/opensafely-core/osrelease/blob/b1ea10bf6a872acd3b5bae5b02ad379cd6699969/publisher/upload.py#L47-L55

This will allow us to generate accurate usage metrics as per:
 * https://github.com/opensafely-core/airlock/issues/48

**Comment by bloodearnest** [comment]
Yep, I have this almost ready to submit, FYI

**Comment by bloodearnest** [comment]
Added in #60
