### ISSUE TITLE
Store manifest.json information in the database

### ISSUE THREAD

**Issue by rebkwok** [opensafely-core/airlock#303]
We want to use the information from the manifest.json file as the source of truth for file data (size, commit etc). However, the manifest.json only contains information about the latest output files. If a job is re-run after a release request is created, we lose the old data from the manifest.json.

Issues #267 and #243 will need this.

RequestFile should grow attributes:
- timestamp
- size
- job_id
- commit
- row_count (pending https://github.com/opensafely-core/job-runner/pull/727)
- col_count (pending https://github.com/opensafely-core/job-runner/pull/727)

And `add_file_to_request()` should read these from the current manifest.json and store them on the RequestFileMetadata object.

manifest.json also has the content_hash, so we can use that when creating the file_id too.

**Comment by madwort** [comment]
If a manifest.json usually only contains the information about the files generated in the most recent job, will we still have problems with orphaned files if a researcher runs more than one job in a workspace before creating a release request? In other words, this proposal fixes the scenario:

* researcher runs job, generates files a&b, manifest contains a&b
* researcher creates release request, airlock stores metadata a&b
* researcher runs another job, generates file c, manifest contains c
* researcher updates release request, airlock stores metadata c

but we have a problem with:

* researcher runs job, generates files a&b, manifest contains a&b
* researcher runs another job, generates file c, manifest contains c
* researcher updates release request, airlock stores metadata c
* a&b are orphans

**Comment by madwort** [comment]
do we need `manifest-JOB_ID.json`?

**Comment by rebkwok** [comment]
> - researcher runs job, generates files a&b, manifest contains a&b
> - researcher runs another job, generates file c, manifest contains c
> - researcher updates release request, airlock stores metadata c
> - airlock has metadata for c, a&b are orphans

I don't think this is true.  Job-runner [reads an existing manifest file, if it exists](https://github.com/opensafely-core/job-runner/blob/main/jobrunner/executors/local.py#L850), and then updates it with data for any new output files. So when the job runs first, manifest contains a & b, when another job runs, it reads the existing manifest and updates it with c; so manifest contains a, b and c, a & b from job 1 and c from job 2.
Hmm. Right, so when a job runs and generates a manifest.json, that only contains info about the output files generated from that specific job? And it overwrites any other manifest.json in the workspace.

**Comment by madwort** [comment]
ah great, yep, that's fine then.

**Comment by evansd** [comment]
> manifest.json also has the content_hash, so we can use that when creating the file_id too.

Given that it's relatively cheap to recompute the hash I wonder if we should do that and check it against what we expect in the manifest. I think there's technically a race condition here in that it would be possible to end up with a file that doesn't match the contents of the manifest if you added it mid-way through the update. Re-computing the hash and checking it against the manifest would at least tell us that that had happened and let us reject the file.

And apart from theoretical race conditions, it feels like a good guard against bugs more generally (e.g. the manifest failing to update for some reason).
