### ISSUE TITLE
Make it easy to update the version of a file in a release request

### ISSUE THREAD

**Issue by inglesp** [opensafely-core/airlock#338]
If a file is added to a release request, and then a new version of the file is produced by running a job, then in order to update the release request to include the new version, a researcher must withdraw the old version from the request and add the new version.  It would be better if they could click a single button to update the version in a request.

When this is fixed, we can update the documentation on how to update files.

Depends on #265.

fixed by https://github.com/opensafely-core/airlock/pull/390

**Comment by madwort** [comment]
Nb. at the moment it is not possible to update a file as described in our docs once a request has been submitted.

If the request is "pending" & a file is "withdrawn", the file is deleted from the request & an updated file can be added to the request as expected.

If the request is "submitted" & a file is "withdrawn", the file remains part of the request with the withdrawn state. If you then try to "add" an updated file, it will error that the file is of a different type (this seems intended to verify that output files are not switched to supporting files, but is actually catching the withdrawn state).

**Comment by bloodearnest** [comment]
Ugh, yes.

I think this needs changing to understand the RETURNED new state when it lands

**Comment by bloodearnest** [comment]
That's how I expected it would look in my head.

And updated file should replace the old file.  

We still have the old contents on disk if we want to expose them in future, but for now I think they should just disappear.

**Comment by madwort** [comment]
nb. if we delete the file from the request, we also need to delete reviews of the old version from the db. I think this is fine as they're still in the audit log?

**Comment by bloodearnest** [comment]
We don't need to delete them - they are attached to a RequestFile that is no longer part of the active request?

**Comment by madwort** [comment]
As briefly discussed at the retreat, the updated file is a new request file with no associated reviews, but we have the "request file names are unique within a request" constraint, so we can't currently add an updated file while a withdrawn file of the same name exists. I had been working on deleting the old RequestFile (& therefore deleting the associated reviews which are behind a foreign key), but spitballing alternatives:

1. relax the "one filename per request" to "one non-withdrawn filename per request". In the UI, only show withdrawn files if there is no file with an active state of the same name in the request. 
2. detach the request file for the old file_id from the request (& leave it orphaned??)
3. attach the RequestFile to a "Round" object & something something allow deleting it from the current round but not previous rounds. you could then in future do something like "Time Machine" & replay the development of a file & reviews through the rounds?
4. something else

**Comment by madwort** [comment]
Discussed with @bloodearnest & we decided to go with deleting the old requestfile for now, as implemented already. All the info is stored in the audit log, so could be reconstructed in future if necessary.

**Comment by madwort** [comment]
related https://github.com/opensafely-core/airlock/issues/446
