### ISSUE TITLE
Record when files are released

### ISSUE THREAD

**Issue by bloodearnest** [opensafely-core/airlock#344]
Currently, when we release files, we only audit and change the state of the request, not the individual files.

We should 
- [x] a) emit an audit event for each file #358 
- [x] b) mark in the db when/who released the file. #365

In future work, this will allow us to show (in the tree and in contents) that a file you are viewing has been already been released. And we can prevent you from adding that file *as an output file* to a new request.

**Comment by madwort** [comment]
> And we can prevent you from adding that file to a new request.

Seems good in principle but wondering about edge cases, e.g. if there was a file that has been released as an output file & then a researcher wanted to add it as a supporting file to a future release request?

**Comment by bloodearnest** [comment]
Good point. I don't think at affects this ticket, but will any future one about adding files based on this. Worth writing that up now?

**Comment by madwort** [comment]
emitting an audit log event may be trickier than I first thought, as [release_files is using old_api](https://github.com/opensafely-core/airlock/blob/main/airlock/business_logic.py#L1353-L1358)
