### ISSUE TITLE
Change "rejected" to "changes requested"

### ISSUE THREAD

**Issue by inglesp** [opensafely-core/airlock#373]
Output checkers have told us that they're unsure what "rejected" means.  Rejection sounds final, and apparently rejecting an output outright has been very rare.

Instead, we should change what we display to "request changes"/"changes requested".

An alternative would be to have three states: "approved", "changes requested", "rejected".  But given how rare outright rejection is, this feels like a waste of valuable screen space.

- [x] change the wording in the UI #377
- ~migrate the ENUM to a matching value (later, not necessarily for beta)~ moved to a new ticket

**Comment by madwort** [comment]
we think this is about files, not release requests

**Comment by madwort** [comment]
closing this as done & creating a new ticket for the Enum refactor to follow
