### ISSUE TITLE
Ensure that output checkers know when work is required

### ISSUE THREAD

**Issue by inglesp** [opensafely-core/airlock#402]
When a request is submitted or resubmitted (ie when it transitions into the SUBMITTED state), output checkers need to be notified so that they can review the request.

We should create or update a GitHub issue, and then ensure that this change is posted to the right channel in Slack.

As part of this work, we should check that when work on the request is finished, we should close the issue.

**Comment by rebkwok** [comment]
Most of this is already done - submitting creates an issue, releasing/withdrawing closes the issue. The re-submitting is the part that needs to be handled. PR #405 and the corresponding job-server PR[ ](https://github.com/opensafely-core/job-server/pull/4381) update the issue with a comment when a request is re-submitted. For this issue, we just need to check that github issue updates are posted to slack (and if they get posted into the thread for the original issue).

Also might need to consider orgs that use a different repo (i.e. Bristol) and possibly don't have slack integrations  that notify them

**Comment by rebkwok** [comment]
Confirmed that updates (i.e. comments) do NOT get posted to slack automatically
