### ISSUE TITLE
Problem with CSV rendering

### ISSUE THREAD

**Issue by inglesp** [opensafely-core/airlock#408]
Both CSVs in [this request](https://github.com/ebmdatalab/opensafely-output-review/issues/884) are "displaying as one long column".

Reported [here](https://bennettoxford.slack.com/archives/C065F8P58AW/p1718974426520819).

**Comment by rebkwok** [comment]
I've had a look at one of the files, and I think this is a problem with the formatting of the data in the file, not with the CSV displaying. Mainly - it's not a comma-separated file with tabular data.  Example format looks something like:

```
               Matched COVID-19
Age 
18-39            1000            1000
40-49            1000            1000
Sex
Female         1000            1000
Male             1000            1000
```

So reading it as a CSV, it gets interpreted as a single column of data.

An example stata file that produces one of these is here: https://github.com/opensafely/post-covid-kidney-outcomes/blob/main/analysis/descriptive_asthma_ethnicity_2017.do#L9
It's tab-separated, and includes titles by using empty tabs, so it's just not really readable as a CSV.
