### ISSUE TITLE
Workspace files are added to a new request instead of a returned request

### ISSUE THREAD

**Issue by madwort** [opensafely-core/airlock#424]
Just noticed something & I’m not sure if it’s a nit or a feature… am I holding something wrong or is this what it’s supposed to do?

steps to reproduce:

* a request is returned to the researcher
* the researcher is viewing the workspace
* the researcher hits “add file”

observed behaviour:

* a new request is created & the file is added to the new request

expected behaviour:
* the file is added to the returned request

**Comment by madwort** [comment]
@rebkwok says:

> Bug - looks like get_active_requests_for_workspace_by_user in local_db needs to be updated to look for PENDING, SUBMITTED and RETURNED requests
>
> Although, we'll need to handle the case where there's a submitted and returned one, I think.  A user can create a new request when they have one that's submitted. If the submitted one is then returned, they'll have two that are considered "active" and the bll get_current_request will raise an exception

**Comment by rebkwok** [comment]
Actually, I was wrong about having to handle multiple active requests. If you have a pending OR submitted one, you can't create a new one, so if we just add returned to that list of "active" requests, we should be fine.

**Comment by rebkwok** [comment]
Summarising [slack discussion](https://bennettoxford.slack.com/archives/C069YDR4NCA/p1719572010815829):

- an "active" request is one that is in any editable status, by either author or reviewer (this includes the newer RETURNED, PARTIALLY_REVIEWED and REVIEWED statuses); `get_active_requests_for_workspace_by_user` needs to be updated to reflect this
- Adding files to a request is not allowed if the request is currently in a reviewer-owned status (this should work as expected)
- Withdrawing files is currently allowed in any non-final status; this should be updated to only be allowed in author-owned status (same as for adding files)
- We will remove the currently allowed state transition from REJECTED to APPROVED; it could potentially allow a user to end up with two active requests, it's not accessible from the UI, and with the extra stages of rounds of review, it's less like that there would be an accidental rejection
