### ISSUE TITLE
Error displaying PDFs

### ISSUE THREAD

**Issue by madwort** [opensafely-core/airlock#469]

**Comment by inglesp** [comment]
PDFs shouldn't be viewable in L4.

**Comment by rebkwok** [comment]
PDFs are valid filetypes: https://github.com/opensafely-core/pipeline/blob/main/pipeline/constants.py#L16

**Comment by rebkwok** [comment]
PDFs are NOT valid filetypes, closed in favour of https://github.com/opensafely-core/pipeline/issues/312
