### ISSUE TITLE
Gather and present metrics about Airlock use

### ISSUE THREAD

**Issue by inglesp** [opensafely-core/airlock#48]
We have [a dashboard](https://dashboards.opensafely.org/d/ccbb7749-65ac-4b15-9ee1-6a442cc245df/output-checking?orgId=1) of charts showing information about output checking.

It would be good to be able to break some of these (eg [files released per week](https://dashboards.opensafely.org/d/ccbb7749-65ac-4b15-9ee1-6a442cc245df/output-checking?orgId=1&viewPanel=13)) down by whether the output request was handled by Airlock or not.

To do this, we need to:

- [x] record, in job-server, whether a released file came from Airlock
- [x] update, in grafana, update the files released per week chart to show the number of files released with and without Airlock
- [x] consider whether there are other charts that are worth updating

**Comment by evansd** [comment]
I've created an initial chart here:
https://dashboards.opensafely.org/d/ccbb7749-65ac-4b15-9ee1-6a442cc245df/output-checking?orgId=1&editPanel=25&tab=query&showCategory=Data%20links

Driven from this query:
```sql
SELECT
  date_trunc('week', rf.created_at) as created_at,
  COALESCE(rf.metadata->>'tool', 'unknown') as tool,
  count(*) as num_files
FROM jobserver_releasefile rf
GROUP BY
  date_trunc('week', rf.created_at),
  COALESCE(rf.metadata->>'tool', 'unknown')
```

As you'll see, the chart is not formatted as it should be but I couldn't work out how to format it correctly in a sensible amount of time, and I assume someone else will be able to show me.

`osrelease` sets the `tool` field in the metadata for both the Release and ReleaseFile objects to `"osrelease"`:
https://github.com/opensafely-core/osrelease/blob/b1ea10bf6a872acd3b5bae5b02ad379cd6699969/publisher/upload.py#L47-L55

We need to ensure that Airlock sets the equivalent fields to `"airlock"` when we integrate it with the releases API.
