### ISSUE TITLE
Add instructions to context + controls fields

### ISSUE THREAD

**Issue by inglesp** [opensafely-core/airlock#630]
On the form for adding the context + controls we should provide some more, ahem, context.

Context (from #403):

> Please describe the contents of this output to help reviewers. This includes:
> 
> * Variable descriptions
> * A description and count of the underlying population for each output if it is not included in the output.
> * Specify population size and degrees of freedom for all regression outputs.
> * Relationship to other data/tables which through combination may introduce secondary disclosive risks.

Controls: see Louis's comment below.

**Comment by LFISHER7** [comment]
Suggested content for the controls section:

> Please describe the statistical disclosure controls you have applied to this output. This includes:
> * The threshold used for low number suppression.
> * The rounding approach used.
